# -*- coding: utf-8 -*-
"""fixxx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVfO4hMUAkxYbacx_ongFDjhAwV49SaK

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** [Muhammad Rivaditya Azzaka]
- **Email:** [m012b4ky3048@bangkit.academy]
- **ID Dicoding:** [Adit Azzaka]

## Menentukan Pertanyaan Bisnis

## Pertanyaan Bisnis

1. Bagaimana distribusi penggunaan sepeda oleh pengguna kasual dan terdaftar berdasarkan waktu (jam dalam sehari)?

2. Bagaimana pola penggunaan sepeda yang dipengaruhi oleh musim, baik itu oleh pengguna sepeda casual maupun yang registered
   
3. Bagaimana perbandingan tren penggunaan sepeda dalam kurun waktu satu tahun yaitu antara tahun 2011 dan tahun 2012

## Import Semua Packages/Library yang Digunakan

Impor libraries yang diperlukan untuk analisis data, visualisasi data, dan manipulasi waktu, termasuk pandas, numpy, matplotlib, dan seaborn.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

"""## Data Wrangling

### Gathering Data

Memuat dataset harian (day_df) dan dataset per jam (hour_df) dari file CSV. Dataset ini berisi informasi mengenai jumlah pengguna sepeda, kondisi cuaca, dan waktu.
"""

# Load dataset
day_df = pd.read_csv('day.csv')
hour_df = pd.read_csv('hour.csv')

# Setting default visualisasi
plt.style.use('ggplot')
sns.set_theme(style="whitegrid")

# Melihat beberapa baris pertama dataset harian
print(day_df.head())

# Informasi umum dataset harian
print(day_df.info())

# Melihat beberapa baris pertama dataset harian
print(hour_df.head())

# Informasi umum dataset harian
print(hour_df.info())

"""### Assessing Data"""

# Statistik deskriptif dataset harian
print(day_df.describe())

# Mengecek apakah ada missing values
print(day_df.isnull().sum())

# Statistik deskriptif dataset hour
print(hour_df.describe())

# Mengecek apakah ada missing values
print(hour_df.isnull().sum())

"""### Cleaning Data

Menghapus duplikasi data (jika ada)
"""

day_df.drop_duplicates(inplace=True)
hour_df.drop_duplicates(inplace=True)

"""Beberapa informasi dalam beberapa kolom kurang jelas atau tidak sesuai dengan pemahaman pengguna, sehingga saya mengubahnya. Agar lebih mudah dipahami, saya juga mengonversi data tertentu, seperti season, month, weekday, dan year, ke dalam bentuk kategorikal."""

# Mengubah beberapa informasi pada kolom
hour_df.rename(columns={
    'dteday': 'dateday',
    'yr': 'year',
    'mnth': 'month',
    'cnt': 'count',
    'hr': 'hour'
}, inplace=True)

hour_df.head()

hour_df['month'] = hour_df['month'].map({
    1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'Mei', 6: 'Jun', 7: 'Jul', 8: 'Ags', 9: 'Sep', 10: 'Okt', 11: 'Nov', 12: 'Des'
})

hour_df['season'] = hour_df['season'].map({
    1: 'Semi', 2: 'Panas', 3: 'Gugur', 4: 'Dingin'
})

hour_df['year'] = hour_df['year'].map({
    0: '2011', 1: '2012'
})

hour_df['weekday'] = hour_df['weekday'].map({
    0: 'Minggu', 1: 'Senin', 2: 'Selasa', 3: 'Rabu', 4: 'Kamis', 5: 'Jumat', 6: 'Sabtu'
})

hour_df['dateday'] = pd.to_datetime(hour_df['dateday'])

hour_df['season'] = hour_df.season.astype('category')
hour_df['year'] = hour_df.year.astype('category')
hour_df['month'] = hour_df.month.astype('category')
hour_df['holiday'] = hour_df.holiday.astype('category')
hour_df['weekday'] = hour_df.weekday.astype('category')
hour_df['workingday'] = hour_df.workingday.astype('category')

hour_df.head()

hour_df.info()

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Statistik deskriptif untuk variabel numerik
print(day_df.describe())

# Distribusi variabel kategorikal
print(day_df['season'].value_counts())
print(day_df['weathersit'].value_counts())
print(day_df['workingday'].value_counts())

"""Membuat heatmap korelasi untuk memahami hubungan antar variabel numerik dalam dataset. Visualisasi ini membantu dalam memahami seberapa kuat pengaruh tiap variabel terhadap jumlah pengguna sepeda."""

plt.figure(figsize=(10, 8))
correlation_matrix = hour_df.corr(numeric_only=True)
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))
cmap = sns.diverging_palette(220, 10, as_cmap=True)
sns.heatmap(
    correlation_matrix,
    annot=True,
    mask=mask,
    cmap=cmap,
    center=0,
    fmt=".2f",
    square=True,
    linewidths=.5,
    cbar_kws={"shrink": .5},
    xticklabels=correlation_matrix.columns,
    yticklabels=correlation_matrix.columns)

plt.title("Heatmap Korelasi")
plt.show()

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:

### Distribusi Pengguna Kasual dan Terdaftar Sepanjang Hari

Pengguna Kasual: Terlihat bahwa pengguna kasual lebih banyak menggunakan sepeda pada jam siang hingga sore hari, yaitu sekitar pukul 10:00 hingga 18:00. Hal ini menunjukkan pola rekreasi atau kegiatan santai yang dilakukan oleh pengguna kasual.

Pengguna Terdaftar: Pengguna terdaftar memiliki puncak penggunaan pada jam-jam sibuk, seperti pagi (sekitar pukul 8:00) dan sore (sekitar pukul 17:00), menunjukkan penggunaan yang terkait dengan perjalanan kerja.
"""

# Visualisasi penggunaan sepeda berdasarkan jam dan tipe pengguna
plt.figure(figsize=(10, 6))
sns.lineplot(x='hour', y='casual', data=hour_df, label='Pengguna Kasual')
sns.lineplot(x='hour', y='registered', data=hour_df, label='Pengguna Terdaftar')
plt.title('Distribusi Pengguna Kasual dan Terdaftar Sepanjang Hari')
plt.xlabel('Jam dalam Sehari')
plt.ylabel('Jumlah Pengguna Sepeda')
plt.legend()
plt.show()

"""### Pertanyaan 2:

Pengguna sepeda, baik kasual maupun terdaftar, lebih aktif selama musim semi dan musim panas, sementara jumlah pengguna berkurang di musim dingin.
Pengguna Kasual: Menunjukkan sensitivitas yang lebih tinggi terhadap perubahan musim, dengan penurunan penggunaan yang tajam di musim dingin. Hal ini kemungkinan besar dipengaruhi oleh kenyamanan cuaca.
Pengguna Terdaftar: Meski juga menunjukkan penurunan di musim dingin, pengguna terdaftar lebih konsisten menggunakan sepeda sepanjang tahun.
"""

seasonal_usage = hour_df.groupby('season')[['registered', 'casual']].sum().reset_index()
plt.figure(figsize=(10, 6))
bar_width = 0.4
bar_position_reg = [1, 2, 3, 4]
bar_position_cas = [x + bar_width for x in bar_position_reg]

plt.bar(
    bar_position_reg,
    seasonal_usage['registered'],
    label='Registered',
    color='tab:blue',
    width=bar_width
)

plt.bar(
    bar_position_cas,
    seasonal_usage['casual'],
    label='Casual',
    color='tab:red',
    width=bar_width
)

plt.xlabel('Season')
plt.ylabel('Total Penyewa Sepeda')
plt.title('Jumlah Penyewa Sepeda Berdasarkan Musim')

season_labels = sorted(hour_df['season'].unique())
plt.xticks(bar_position_reg, season_labels)

plt.legend()
plt.show()

"""### Pertanyaan 3:

### Perbandingan tren penggunaan sepeda dalam kurun waktu satu tahun yaitu antara tahun 2011 dan tahun 2012

Tren penggunaan sepeda meningkat secara signifikan dari tahun 2011 ke 2012, khususnya pada bulan-bulan musim semi dan musim panas. Hal ini mungkin disebabkan oleh peningkatan popularitas layanan sepeda atau promosi bisnis yang dilakukan pada tahun 2012.
Terlepas dari musim, jumlah pengguna pada tahun 2012 menunjukkan pola penggunaan yang lebih tinggi dibandingkan dengan tahun 2011, yang menunjukkan adanya pertumbuhan pengguna terdaftar atau peningkatan aktivitas dari pengguna kasual.
"""

hour_df['month'] = pd.Categorical(hour_df['month'], categories=[
    'Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des'], ordered=True)

monthly_counts = hour_df.groupby(by=["month", "year"]).agg({"count": "sum"}).reset_index()
sns.lineplot(data=monthly_counts, x="month", y="count", hue="year",
             palette="rocket", marker="o")

plt.title("Total Jumlah Penyewa Sepeda per Bulan dan Tahun")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Total Penyewa Sepeda")

plt.legend(title="Tahun", loc="upper right")
plt.tight_layout()
plt.show()

"""## Conclusion
- Conclusion 1
Distribusi penggunaan sepeda oleh pengguna kasual dan terdaftar menunjukkan pola yang berbeda sepanjang hari. Pengguna terdaftar memiliki puncak penggunaan pada jam sibuk pagi dan sore hari, mengindikasikan bahwa sepeda banyak digunakan sebagai moda transportasi untuk berangkat dan pulang kerja. Sementara itu, pengguna kasual lebih aktif di siang hingga sore hari, yang kemungkinan besar terkait dengan aktivitas rekreasi. Kesimpulan ini dapat membantu bisnis dalam perencanaan logistik, dengan mengalokasikan lebih banyak sepeda di titik-titik yang banyak digunakan pada jam-jam tertentu, terutama bagi pengguna terdaftar.


- Conclusion 2
Pengaruh musim terhadap penggunaan sepeda sangat terlihat, di mana musim semi dan musim panas menjadi periode dengan jumlah penggunaan tertinggi untuk kedua jenis pengguna. Namun, pengguna kasual lebih sensitif terhadap perubahan musim, dengan penurunan tajam selama musim dingin. Sebaliknya, pengguna terdaftar lebih konsisten menggunakan sepeda sepanjang tahun. Bisnis dapat memanfaatkan temuan ini untuk melakukan pemeliharaan sepeda di musim dingin dan meluncurkan promosi khusus yang menargetkan pengguna kasual agar tetap tertarik untuk menggunakan sepeda selama musim tersebut.


- Conclusion 3
Perbandingan penggunaan sepeda antara tahun 2011 dan 2012 menunjukkan adanya pertumbuhan yang signifikan, terutama pada musim semi dan musim panas di tahun 2012. Hal ini mungkin mencerminkan peningkatan popularitas layanan atau keberhasilan promosi pada tahun 2012. Pertumbuhan yang konsisten ini menunjukkan adanya potensi pasar yang lebih besar, sehingga bisnis dapat mempertimbangkan penambahan kapasitas sepeda atau ekspansi layanan di masa depan. Menyusun strategi promosi atau penawaran khusus yang lebih intensif di awal musim semi bisa menjadi langkah strategis untuk memanfaatkan lonjakan permintaan di bulan-bulan tersebut.

"""